### ISSUE TITLE
Extract the screen image and export it through the API

### ISSUE THREAD

**Issue by andrefdre** [andrefdre/Pose-API#11]
Getting the image from the game is already implemented by @zemaria2000 now it's only needed to send it through the API.

**Comment by zemaria2000** [comment]
Some links with methods that could be useful for this particular task:
https://maven.fabricmc.net/docs/yarn-1.17-rc1+build.1/net/minecraft/client/util/ScreenshotRecorder.html
https://maven.fabricmc.net/docs/yarn-1.16.4+build.1/net/minecraft/client/MinecraftClient.html#currentScreen

**Comment by andrefdre** [comment]
This feature was implemented.
