### ISSUE TITLE
Implement the rest API

### ISSUE THREAD

**Issue by andrefdre** [andrefdre/Pose-API#2]
Implement a rest API to export information about the Pose.

**Comment by zemaria2000** [comment]
The latest version of branch "screen functions" implements new api functions, mainly one that can retrieve some key movements from the player. However, it's not fully functional yet.
Also we need to review the get_inventory function, which is not properly counting the amount of each slot

**Comment by andrefdre** [comment]
This feature was implemented using undertow library.
